cp  ~/Dropbox/alfalfaLongitudinal/plots/heritabilityOfVI.pdf plots/
cp  ~/Dropbox/alfalfaLongitudinal/plots/legend0to1.pdf plots/
cp  ~/Dropbox/alfalfaLongitudinal/plots/corByGDD.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurveDeviations_ndvi_yld_h2_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurvesWithMeanCurve_ndvi_yld_h2_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/AUC_ndvi_yld_h2_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurveDeviations_ndvi_yld_h3_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurvesWithMeanCurve_ndvi_yld_h3_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/AUC_ndvi_yld_h3_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurveDeviations_ndvi_yld_h1_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurvesWithMeanCurve_ndvi_yld_h1_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/AUC_ndvi_yld_h1_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurveDeviations_ndvi_yld_h2_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurvesWithMeanCurve_ndvi_yld_h2_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/AUC_ndvi_yld_h2_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurveDeviations_ndvi_CP_h2_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurvesWithMeanCurve_ndvi_CP_h2_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/AUC_ndvi_CP_h2_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurveDeviations_ndvi_NDF_h2_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurvesWithMeanCurve_ndvi_NDF_h2_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/AUC_ndvi_NDF_h2_2019_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurveDeviations_ndvi_CP_h2_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurvesWithMeanCurve_ndvi_CP_h2_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/AUC_ndvi_CP_h2_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurveDeviations_ndvi_NDF_h2_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/growthCurvesWithMeanCurve_ndvi_NDF_h2_2020_geno8.pdf plots/
cp ~/Dropbox/alfalfaLongitudinal/plots/AUC_ndvi_NDF_h2_2020_geno8.pdf plots/
